import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './dialog-form-modal';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import9 from '@angular/core/src/linker/component_factory';
export declare const VEXDialogButtonsNgFactory: import9.ComponentFactory<import3.VEXDialogButtons>;
export declare function viewFactory_VEXDialogButtons0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.VEXDialogButtons>;
export declare const DialogFormModalNgFactory: import9.ComponentFactory<import3.DialogFormModal>;
export declare function viewFactory_DialogFormModal0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.DialogFormModal>;
export declare const FormDropInNgFactory: import9.ComponentFactory<import3.FormDropIn>;
export declare function viewFactory_FormDropIn0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.FormDropIn>;
