import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './message-modal.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import10 from '@angular/core/src/linker/component_factory';
export declare const BSMessageModalTitleNgFactory: import10.ComponentFactory<import3.BSMessageModalTitle>;
export declare function viewFactory_BSMessageModalTitle0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.BSMessageModalTitle>;
export declare const BSMessageModalBodyNgFactory: import10.ComponentFactory<import3.BSMessageModalBody>;
export declare function viewFactory_BSMessageModalBody0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.BSMessageModalBody>;
export declare const BSModalFooterNgFactory: import10.ComponentFactory<import3.BSModalFooter>;
export declare function viewFactory_BSModalFooter0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.BSModalFooter>;
export declare const BSMessageModalNgFactory: import10.ComponentFactory<import3.BSMessageModal>;
export declare function viewFactory_BSMessageModal0(viewUtils: import4.ViewUtils, parentInjector: import5.Injector, declarationEl: import2.AppElement): import1.AppView<import3.BSMessageModal>;
